---
title: "Shiny Analytic Data Product"
author: "Capt Spencer Butt"
date: " r format(Sys.Date(), '%d %B %Y') "
output: github_document
keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 1

### 1.1 Name
IDPS Log Autoencoder Anomaly Detector (IDPS-LAAD)

### 1.2: IDPS-LAAD Title

This analytic data product is designed to construct an Autoencoder Neural Network (ANN) to detect anomalous data observations within Intrusion Detection Prevention System (IDPS) log file data. This analytic will test multiple ANN hyperparameters to determine the optimal settings supporting anomaly detection assuming that anomalous observations correspond to potentially adverse network traffic. 

### 1.3: IDPS Log Autoencoder Anomaly Detector Description

IDPS-LAAD is designed aid expeditious discovery of potentially hostile actions on a computer network protected by various intrusion detection sensors. The IDPS log files are consolidated by independent software systems to be analyzed by human cyber security experts. Most cyber security agencies have a limited cyber security staff, making the review of the number of cyber logs collected during normal day-to-day operations problematic. Additionally, cyber security staffs require a spectrum of analytic tools to analyze cyber security files to limit the probability of hostile cyber actions going undetected.

IDPS-LAAD is a tool to be used by cyber security experts with limited programming experience, and little-to-no statistical and/or machine learning expertise. Users will interact with the program via graphical user interface using keyboard and mouse inputs a with which a standard computer user is familiar. There are no known security concerns nor are there appearance constrains to which the program must adhere. 

IDPS-LAAD is designed to read in a .csv containing the IDPS cyber log. The program will allow users to select what features (variables) in the data they wish to analyze. The program will then automatically prepare the data for ANN analysis. Once the data is prepared for ANN analysis, the IDPS-LAAD will automatically generate a designed experiment to test ANN hyperparameters, and subsequently run ANNs testing each of the hyperparameters. Once the 'optimal' hyperparameters are found the the analytic will analyze the IDPS cyber data and graphically display the results as well as output a user defined top 'n' anomalous observations. 

## Section 2

| Feature | Priority | Status | Value to User | User Inputs | Outputs | Purpose of Output | Sufficient Time to Deadline? | Required in Version? |
| :------ | -------: | :----- | :------------ | :---------- | :------ | :---------------- | :--------------------------- | :------------------- |
| Read in .csv |  5 | Not Started  | Allows user to specify what IDPS log file to analyze for anomalies indicating potential hostile cyber traffic  | File selection  | None  |   |   |   |
| Select Features | 6 | Not Started |  |  |  |  |  |  |
| Format Data for ANN | 7 | Not Started |  |  |  |  |  |  |
| Build Designed Experiment | 8 | Not Started |  |  |  |  |  |  |
| Evaluate ANNs | 1 | Not Started | Enable testing of multiple hyperparameter settings for ANNs to determine optimal settings |  |  |  |  |  |
| Train Final ANN | 2 | Not Started |  |  |  |  |  |  |
| Display Anomalous | 3 | Not Started |  |  |  |  |  |  |
| Display top 'n' Anomalous | 4 | Not Started |  |  |  |  |  |  |



IDPS-LAAD will perform the following functions:

1. Read in a .csv file composed of individual IDPS cyber log observations described by features

2. Allow the user to select which features the user wants to retain for analysis

3. Automatically convert the selected features into a format compatible with Autoencoder Neural Networks
    i) Adjust for missing data
        A.  Add a missing column for Port Numbers and IP Addresses with a value of '1' where that data is missing
        B.  Missing categorical data will be flagged with a 'missing' label
    ii) One-Hot Encode Categorical Features
    iii) Convert IP Addresses into 32-bit binary number, each column containing one bit
    iiii) Scale the data frame
    iiiii) Split the data frame into training and test data frames

4. Construct a designed experiment to test ANN hyperparameters

5. Evaluate the ANNs using the hyperparameters in 4.

6. Automatically select the optimal hyperparameters and build an ANN using those hyperparameters

7. Graphically display via histogram anomalous observations using the ANN built in 6. 

8. Output a user specified top 'n' anomalous observations


